---
- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python
    - python-setuptools
    - python-dev
    - build-essential
    - python3-pip
