---
- name: Install Flask package
  ansible.builtin.pip:
    name: flask
    state: present

- name: Copy app.py file
  ansible.builtin.copy:
    src: "./app.py"
    dest: "/opt/app.py"
    owner: root
    group: root
    mode: '0644'

- name: Copy environment file
  ansible.builtin.copy:
    src: "../../.env"
    dest: "/opt/.env"
    owner: root
    group: root
    mode: '0644'

- name: Stop Flask server if running
  ansible.builtin.command: pkill -f "flask"
  register: flask_web_stop_result
  ignore_errors: true
  changed_when: flask_web_stop_result.rc == 0
  failed_when: flask_web_stop_result.rc not in [0, 1]

- name: Start Flask server with environment variables
  ansible.builtin.shell: |
    set -a
    source /opt/.env
    set +a
    FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 > /opt/flask.log 2>&1 &
  args:
    executable: /bin/bash
  changed_when: true
